### ISSUE TITLE
It's not intuitive how to add notes

### ISSUE THREAD

**Issue by paulrosen** [rualark/AiHarmony#1]
I'm sure I'm missing something obvious, but that is sort of the point of this issue...

I can't figure out how to add a note. I click on a note shape on the top, then click on the music, but it adds a *rest* instead of a note. I can't figure out if there is a way to change a rest into a note.

**Comment by rualark** [comment]
Thanks, I am receiving the same information from other users.

Currently the notes are input using pitch buttons on mobile touchscreens (they do not show on desktops) and using A B C D E F G keys on desktop keyboard, like in any notation software. This is usually fast and simple, but not always intuitive.

I can think of several solutions to this problem:
1. Show notification when pause is selected, that user can press a key (or use a button on mobile).
**2. Add buttons A B C D E F G on desktops too, not only on mobiles. This will take some space, but will make interface more unified.**
3. Add one button "Note" to convert pause to note. The problem with this button is that there are already buttons with note images, which change length. It is not easy to think of a button that will mean "some note" and will not make interface difficult.
4. Add one button "C" to convert pause to note C. This seems to both save space and be more intuitive, but is strange.
5. I can make pause button triggering instead of advancing when pause is selected. Currently it inputs pause and moves to next note like in notation software. This will allow to convert pause to an arbitrary note, but the idea of "arbitrary note" is already strange.
6. Allow to drag pauses, which will result in pauses. Really? Not sure that user will try to drag a pause.
7. Allow to double click a pause to convert to arbitrary note. Strange.
8. Show "ghost note" when mouse hovering over abcjs div. Clicking will input this note. Difficult approach in all aspects and also will make selecting things more difficult. This approach is used in most advanced notation software, where different modes (select or input) are used. Not sure we need this.
8. Show note when hovering over selected pause, like flat.io does. This seems too unclear for simple interface, I think.

So far I will go with variant 2, until we choose a better one.

Actually, A B C D E F G buttons are not 100% intuitive about what they do. Usually people think of chords or modes when seeing these letters. I am looking forward to make them more intuitive:
1. Show clickable part of piano keyboard. Problem with this approach is that currently like in notation software you press Sharp and then Note to input it. Instead, if you press Sharp and then click on white key, this is not intuitive if editor should input note with sharp or without. Another problem is that people tend to think about octaves when they see part of piano keyboard and what octave is shown is not known.
2. Like in flat.io, I could show a scrollable piano keyboard, but this takes too much space on touchscreen.
**3. Make A B C D E F G buttons resemble piano keys or noteheads stylistically. Seems best solution so far, but it makes design a little glutted.**

I'll try to draw something.
